"""Coluna livro aceita 255 caracteres

Revision ID: 96119e684db2
Revises: 546655a12ccc
Create Date: 2023-02-18 11:28:57.469134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96119e684db2'
down_revision = '546655a12ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('livro',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.alter_column('livro',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###
